service: hc-platform-github-app-test

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    APP_ID: <github-app-id>
    PRIVATE_KEY: <github-rsa-key>
    WEBHOOK_SECRET: <github-webhook-secret>
    NODE_ENV: production
    LOG_LEVEL: debug

functions:
  webhooks:
    handler: handler.webhooks
    events:
      - httpApi:
          path: /api/github/webhooks
          method: post